# Generated by Django 5.1.5 on 2025-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
            ],
        ),
    ]
